### ISSUE TITLE
No Sound!

### ISSUE THREAD

**Issue by brianzp** [TesseractTeam/Genisys#1]
### Issue description

There are no sounds on the server.

### Steps to reproduce the issue

Goto the server, walk on grass, open the door, go under water, break blocks there will no sounds produced.

### OS and versions

* Genisys: v1.0.7
* PHP: 7.0.9
* Server OS: Linux, linux
* Game version: v1.0.7

### Crashdump, backtrace, memory dumps, plugins list or other files

none.

**Comment by poustmal** [comment]
Software doesn't have resource pack support,that's why.
